{{- define "application-chart.service.yaml" -}}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ .application.name | default .Release.Name }}-{{ .env }}-svc
  namespace: {{ .Release.Namespace | default "default" }}
  annotations:
    application: {{ .Release.Name }}
  {{- if (.application.monitoring).enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
  {{- end }}
  labels:
    run: {{ .application.name }}
  {{- if (.application.monitoring).enabled }}
    release: prometheus
  {{- end }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ .application.port | default 3000 }}
    protocol: TCP
  selector:
    app: {{ .application.name }}-{{ .env }}
  type: ClusterIP

---

{{ end }}
