{{- define "base-api-chart.configMap.tpl" -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.application.name | default .Release.Name }}-cm
  namespace: {{ .Values.application.namespace | default .Release.Namespace | default "default" }}
data:
  {{ range .Values.application.env }}
  {{ . }}
  {{- end -}}

{{- end -}}