{{- define "base-api-chart.deployment.tpl" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name | default .Release.Name }}
  namespace: {{ .Values.application.namespace | default .Release.Namespace | default "default" }}
  creationTimestamp: null
  labels:
    app: {{ .Values.application.name }}
    release: prometheus
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.application.name }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Values.application.name }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        name: {{ .Values.application.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ if .Values.env }}env:
{{ toYaml .Values.env | indent 8 }}{{ end }}{{ if .Values.envFromTerraform }}
{{ toYaml .Values.envFromTerraform | indent 8 }}{{ end }}
        resources: {}
        ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: docker-cfg
status: {}

{{ end }}
