{{- define "base-api-chart.service.tpl" -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}-svc
  namespace: {{ .Values.application.namespace | default "default" }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/scheme: "http"
  labels:
    run: {{ .Values.application.name }}
    release: prometheus
spec:
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  selector:
    app: {{ .Values.application.name }}
  type: ClusterIP

{{ end }}
