
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: argocd-server-ingress
#   namespace: argocd
#   annotations:
#     kubernetes.io/ingress.class: argocd-nginx
#     cert-manager.io/cluster-issuer: letsencrypt-prod
#     kubernetes.io/tls-acme: "true"
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#     nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#     service.beta.kubernetes.io/do-loadbalancer-hostname: argocd.bhc-it.online
#     service.beta.kubernetes.io/scw-loadbalancer-use-hostname: "true"
# spec:
#   rules:
#   - host: argocd.bhc-it.online
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: argocd-server
#             port:
#               name: https
#   tls:
#   - hosts:
#     - argocd.bhc-it.online
#     secretName: argocd-secret