{{- define "base-api-chart.deployment.tpl" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.application.name }}-dep
  namespace: {{ .Values.application.namespace | default "default" }}
  creationTimestamp: null
  labels:
    app: rest-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rest-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rest-api
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        name: api
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources: {}
        ports:
          - containerPort: 3000
      imagePullSecrets:
        - name: docker-cfg
status: {}

{{ end }}
